export const GroupedSets = [
  {
    label: 'Standard',
    value: 'displays',
    items: [
      { label: 'BT1', value: 'BT1' },
      { label: 'BT2', value: 'BT2' },
      { label: 'BT3', value: 'BT3' },
      { label: 'BT4', value: 'BT4' },
      { label: 'BT5', value: 'BT5' },
      { label: 'BT6', value: 'BT6' },
      { label: 'BT7', value: 'BT7' },
      { label: 'BT8', value: 'BT8' },
      { label: 'BT9', value: 'BT9' },
      { label: 'BT10', value: 'BT10' },
    ],
  },
  {
    label: 'Extra',
    value: 'extra',
    items: [
      { label: 'EX1', value: 'EX1' },
      { label: 'EX2', value: 'EX2' },
      { label: 'EX3', value: 'EX3' },
    ],
  },
  {
    label: 'Starter Decks',
    value: 'starter',
    items: [
      { label: 'ST1', value: 'ST1' },
      { label: 'ST2', value: 'ST2' },
      { label: 'ST3', value: 'ST3' },
      { label: 'ST4', value: 'ST4' },
      { label: 'ST5', value: 'ST5' },
      { label: 'ST6', value: 'ST6' },
      { label: 'ST7', value: 'ST7' },
      { label: 'ST8', value: 'ST8' },
      { label: 'ST9', value: 'ST9' },
      { label: 'ST10', value: 'ST10' },
      { label: 'ST12', value: 'ST12' },
      { label: 'ST13', value: 'ST13' },
    ],
  },
];

export const CardTypes: string[] = ['Digi-Egg', 'Digimon', 'Tamer', 'Option'];

export const Keywords: string[] = [
  '\uff1cArmor Purge\uff1e',
  '\uff1cBlitz\uff1e',
  '\uff1cBlocker\uff1e',
  '\uff1cDecoy (Black)\uff1e',
  '\uff1cDecoy (Black/White)\uff1e',
  '\uff1cDecoy (Red)(Black)\uff1e',
  '\uff1cDecoy (D-Brigade)\uff1e',
  '\uff1cDe-Digivolve 1\uff1e',
  '\uff1cDe-Digivolve 2\uff1e',
  '\uff1cDe-Digivolve 3\uff1e',
  '\uff1cDe-Digivolve 4\uff1e',
  '\uff1cDelay\uff1e',
  '\uff1cDigi-Burst 1\uff1e',
  '\uff1cDigi-Burst 2\uff1e',
  '\uff1cDigi-Burst 3\uff1e',
  '\uff1cDigi-Burst 4\uff1e',
  '\uff1cDigi-Burst up to 4\uff1e',
  '\uff1cDigisorption -2\uff1e',
  '\uff1cDigisorption -3\uff1e',
  '\uff1cDigisorption\uff1e',
  '\uff1cDraw 1\uff1e',
  '\uff1cDraw 2\uff1e',
  '\uff1cDraw 3\uff1e',
  '\uff1cEvade\uff1e',
  '\uff1cJamming\uff1e',
  '\uff1cMaterial Save 1\uff1e',
  '\uff1cMaterial Save 2\uff1e',
  '\uff1cMaterial Save 3\uff1e',
  '\uff1cPiercing\uff1e',
  '\uff1cReboot\uff1e',
  '\uff1cRecovery +1 (Deck)\uff1e',
  '\uff1cRecovery +2 (Deck)\uff1e',
  '\uff1cRetaliation\uff1e',
  '\uff1cRush\uff1e',
  '\uff1cSave\uff1e',
  '\uff1cSecurity Attack +1\uff1e',
  '\uff1cSecurity Attack +2\uff1e',
  '\uff1cSecurity Attack -1\uff1e',
  '\uff1cSecurity Attack -2\uff1e',
  '\uff1cSecurity Attack -3\uff1e',
];

export const Colors: string[] = [
  'Red',
  'Blue',
  'Yellow',
  'Green',
  'Black',
  'Purple',
  'White',
  'Multi',
];

export const ColorsWithoutMulti: string[] = [
  'Red',
  'Blue',
  'Yellow',
  'Green',
  'Black',
  'Purple',
  'White',
];

export const Forms: string[] = [
  'In-Training',
  'Rookie',
  'Champion',
  'Ultimate',
  'Mega',
  'Hybrid',
  'Armor Form',
  'D-Reaper',
];

export const Attributes: string[] = [
  'Data',
  'Vaccine',
  'Virus',
  'Free',
  'Variable',
  'Unknown',
];

export const Types: string[] = [
  'Abnormal',
  'Alien Humanoid',
  'Amphibian',
  'Ancient Animal',
  'Ancient Bird',
  'Ancient Birdkin',
  'Ancient Dragon',
  'Ancient Dragonkin',
  'Ancient Fish',
  'Ancient Holy Warrior',
  'Ancient Insect',
  'Ancient Mineral',
  'Ancient Mythical Beast',
  'Ancient Plant',
  'Ancient',
  'Angel',
  'Ankylosaur',
  'Aquabeast',
  'Aquatic',
  'Archangel',
  'Armor',
  'Authority',
  'Avian',
  'Baby Dragon',
  'Beast Dragon',
  'Bagra Army',
  'Beast Knight',
  'Beast',
  'Beastkin',
  'Big Death-Stars',
  'Bird Dragon',
  'Bird',
  'Birdkin',
  'Blue Flare',
  'Boss',
  'Bulb',
  'CRT',
  'Carnivorous Plant',
  'Ceratopsian',
  'Cherub',
  'Composite',
  'Crustacean',
  'Cyborg',
  'D-Brigade',
  'Dark Animal',
  'Dark Dragon',
  'Dark Knight',
  'Demon Lord',
  'Demon',
  'Deva',
  'Dinosaur',
  'Dragon Warrior',
  'Dragon',
  'Dragonkin',
  'Earth Dragon',
  'Elusive Beast',
  'Evil Dragon',
  'Evil',
  'Fairy',
  'Fallen Angel',
  'Fire Dragon',
  'Flame',
  'Four Great Dragons',
  'Four Sovereigns',
  'Ghost',
  'Giant Bird',
  'General',
  'Holy Beast',
  'Holy Bird',
  'Holy Dragon',
  'Holy Sword',
  'Holy Warrior',
  'Ice-Snow',
  'Insectoid',
  'Invader',
  'Larva',
  'LCD',
  'Legend-Arms',
  'Lesser',
  'Light Dragon',
  'Machine Dragon',
  'Machine',
  'Magic Knight',
  'Magic Warrior',
  'Major',
  'Mammal',
  'Mine',
  'Mineral',
  'Mini Angel',
  'Mini Bird',
  'Mini Dragon',
  'Minor',
  'Mollusk',
  'Monk',
  'Musical Instrument',
  'Mutant',
  'Mysterious Beast',
  'Mysterious Bird',
  'Mythical Beast',
  'Mythical Dragon',
  'Olympos XII',
  'Perfect',
  'Plesiosaur',
  'Puppet',
  'Reptile',
  'Rock Dragon',
  'Rock',
  'Royal Knight',
  'Sea Animal',
  'Sea Beast',
  'Seraph',
  'Seven Great Demon Lords',
  'Shaman',
  'Sky Dragon',
  'Super Major',
  'Ten Warriors',
  'Three Great Angels',
  'Three Musketeers',
  'Throne',
  'Twilight',
  'Undead',
  'Unidentified',
  'Unique',
  'Unknown',
  'Vegetation',
  'Virtue',
  'Warrior',
  'Weapon',
  'Wizard',
  'X Antibody',
  'Xros Heart',
].sort();

export const Illustrators: string[] = [
  '61',
  "As'Maria",
  'Atarime',
  'banira',
  'DAI-XT.',
  'funbolt',
  'Gosha',
  'GOSSAN',
  'Hisashi Fujiwara',
  'Hokyyuu',
  'Ishibashi Yosuke',
  'itohiro',
  'Kayo Horaguchi',
  'kaz',
  'Kazumasa Yasukuni',
  'Kenji Watanabe',
  'Kirita',
  'KISUKE',
  'koki',
  'MATSUMOTO EIGHT',
  'Minato Sashima',
  'mojuke',
  'Nakano Haito',
  'Naochika Morishita',
  'Okada Anmitsu',
  'p!k@ru',
  'poroze',
  'Qacoro',
  'Ryodan',
  'Ryuda',
  'Sanosuke Sakuma',
  'sasasi',
  'satsuki may',
  'SENNSU',
  'Shigeo Niwa',
  'Shin Sasaki',
  'shosuke',
  'Spareribs',
  'sunohara',
  'Takase',
  'Takumi Kousaka',
  'TANIMESO',
  'Teppei Tadokoro',
  'tessy',
  'Tomotake Kinoshita',
  'Tonamikanji',
  'toriyufu',
  'TSCR',
  'Tsunemi Aosa',
  'tyuga',
  'UnnoDaisuke',
  'YAMURETSU',
  'Yuki Mukai',
  'yuuki.'
].sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()));

export const Lvs: string[] = ['Lv.2', 'Lv.3', 'Lv.4', 'Lv.5', 'Lv.6', 'Lv.7'];

export const Rarities: string[] = ['C', 'U', 'R', 'SR', 'SEC', 'P'];

export const Versions: string[] = ['Normal', 'AA', 'Stamp', 'Pre-Release'];

export const SpecialRequirements: string[] = [
  'Digivolve',
  'DNA Digivolution',
  'DigiXros',
];

export const Restrictions: string[] = ['Banned', 'Restricted to 1'];

export const Sources: string[] = [
  '\u25b9RELEASE SPECIAL BOOSTER Ver.1.0\u3010BT01-03\u3011',
  '\u25b9RELEASE SPECIAL BOOSTER Ver.1.5\u3010BT01-03\u3011',
  '\u25b9BOOSTER -GREAT LEGEND- [BT04]',
  '\u25b9BOOSTER -BATTLE OF OMNI- [BT05]',
  '\u25b9BOOSTER DOUBLE DIAMOND [BT-06]',
  '\u25b9BOOSTER -NEXT ADVENTURE- [BT-07]',
  '\u25b9BOOSTER -NEW AWAKENING- [BT08]',
  '\u25b9BOOSTER X RECORD [BT-09]',
  '\u25b9BOOSTER XROS ENCOUNTER [BT-10]',

  '\u25b9THEME BOOSTER -CLASSIC COLLECTION-[EX-01]',
  '\u25b9theme booster DIGITAL HAZARD [EX-02]',

  '\u25b9Starter Deck, GAIA RED\u3010ST-1\u3011',
  '\u25b9Starter Deck, COCYTUS BLUE\u3010ST-2\u3011',
  '\u25b9Starter Deck, HEAVEN\u2019S YELLOW\u3010ST-3\u3011',
  '\u25b9Starter Deck, GIGA GREEN[ST-4]',
  '\u25b9Starter Deck, MACHINE BLACK[ST-5]',
  '\u25b9Starter Deck, GALLANTMON [ST-7]',
  '\u25b9Starter Deck, VENOMOUS VIOLET[ST-6]',
  '\u25b9Starter Deck, PARALLEL WORLD TACTICIAN [ST-10]',
  '\u25b9Starter Deck, ULFORCEVEEDRAMON [ST-8]',
  '\u25b9Starter Deck, ULTIMATE ANCIENT DRAGON  [ST-9]',
  '\u25b9start deck JESMON[ST-12]',
  '\u25b9start deck RAGNALOARDMON[ST-13]',
  "DIGIMON CARD TAMER'S EVOLUTION BOX\uff3bPB-01\uff3d",
  '1-Year Anniversary Promo Pack',
  '2021 Champion Card Set',
  '2021 Championship Finals Tamer\u2018s Evolution Pack',
  '2021 Finalist Card Set',
  '2021 Online Regionals Participant Pack',
  '2021 Vault Set',
  '2021 World Championship Participation Card',
  'April Ultimate Cup Champion',
  'April Ultimate Cup Top 128',
  'April Ultimate Cup Top 2',
  'April Ultimate Cup Top 32',
  'April Ultimate Cup Top 64',
  'April Ultimate Cup Top 8',
  'BATTLE OF OMNI (BT-05) Pre-Release Tournaments',
  'BOOSTER -BATTLE OF OMNI- [BT05] Box Promotion',
  'BOOSTER -DOUBLE DIAMOND- [BT-06] Box Promotion',
  'BOOSTER -GREAT LEGEND- [BT04] Box Promotion',
  'BOOSTER -GREAT LEGEND- [BT04]Errata Card',
  'BOOSTER -NEXT ADVENTURE- [BT-07]Box Toppers',
  'BOOSTER DOUBLE DIAMOND [BT-06] Errata Card',
  'Box Promotion Pack -Next Adventure-',
  'DC-1 2022 TOP 8',
  'DC-1 Grand Prix TOP 32',
  'DC-1 Grand Prix TOP 64',
  'DC-1 Grand Prix TOP 8',
  'DC-1 Grand Prix Veemon Participation Set',
  'DIGIMON CARD GAME GALLANTMON [ST-7],DIGIMON CARD GAME ULFORCEVEEDRAMON [ST-8]',
  'DIGIMON CARD GAME PREMIUM PACK SET 01',
  'DOUBLE DIAMOND DASH PACK',
  'DOUBLE DIAMOND DASH PACKErrata Card',
  'DOUBLE DIAMOND(BT-06) Pre-Release Tournament Participation Card',
  'DOUBLE DIAMOND(BT-06) Pre-Release Tournament Winner Card',
  'Dash Pack Ver. 1.0',
  'Dash Pack Ver. 1.5',
  'Digi-Egg Set',
  'Event Pack 2',
  'Event Pack Alt-Art Gold Stamp Set',
  'Event Pack',
  'Fest Set',
  'Fest Stamp SR',
  'Fest WINNER Stamp SR',
  'Great Dash Pack',
  'Great Legend (BT-04) Pre-Release Tournaments',
  'Great Legend Power Up Pack Errata Card',
  'Great Legend Power Up Pack',
  'Judge Pack',
  'July Evolution Cup',
  'June Premier TO Events',
  'NEW AWAKENING\uff08BT-08\uff09Pre-Release Tournament Winner Card',
  'NEW AWAKENING\uff08BT-08\uff09Pre-Release Tournament',
  'NEXT ADVENTURE\uff08BT-07\uff09Pre-Release Tournament, BOOSTER -NEW AWAKENING- [BT08] Box Promotion',
  'Official Tournament Pack VOL.1',
  'Official Tournament Pack Vol.3',
  'Official Tournament Pack Vol.4',
  'Official Tournament Pack Vol.5 Errata Card',
  'Official Tournament Pack Vol.5',
  'Promotion Pack Ver 0.0',
  'RELEASE SPECIAL BOOSTER Ver.1.0\u3010BT01-03\u3011Box Promotion',
  'RELEASE SPECIAL BOOSTER Ver.1.5\u3010BT01-03\u3011Box Promotion',
  'RELEASE SPECIAL BOOSTER Ver.1.5\u3010BT01-03\u3011Errata Card',
  'RELEASE SPECIAL BOOSTER Ver.1.5\u3010BT01-03\u3011Restricted Cards (1)',
  'Special Box Promotion Pack Errata Card',
  'Special Box Promotion Pack',
  'Special Release Memorial Pack',
  'Store Champion Card Set',
  'Store Championship 2022 Champion Card Set',
  'Store Championship 2022 Participant Pack',
  'Store Championship Participant Pack',
  'TAMER\u2019S EVOLUTION BOX2[PB-06]',
  'THEME BOOSTER -CLASSIC COLLECTION-[EX-01] Box Promotion',
  'THEME BOOSTER -DIGITAL HAZRAD-[EX-02] Box Promotion,DIGIMON CARD GAME ADVENTURE BOX [AB-01] Box Promotion',
  'Tamer Battle Pack 1',
  'Tamer Battle Pack Vol.2',
  'Tamer Party Events Vol.2',
  'Tamer Party Vol.3',
  'Tamer Party Vol.4',
  'Tamer Party Vol.5',
  'Tamer Party events',
  'Winner Pack NEXT ADVENTURE',
  'Winner Pack',
];

export const Blocks: string[] = ['00', '01', '02'];
