export const GroupedSets = [
  {
    label: 'Standard',
    value: 'displays',
    items: [
      { label: 'BT1', value: 'BT1' },
      { label: 'BT2', value: 'BT2' },
      { label: 'BT3', value: 'BT3' },
      { label: 'BT4', value: 'BT4' },
      { label: 'BT5', value: 'BT5' },
      { label: 'BT6', value: 'BT6' },
      { label: 'BT7', value: 'BT7' },
      { label: 'BT8', value: 'BT8' },
      { label: 'BT9', value: 'BT9' },
      { label: 'BT10', value: 'BT10' },
    ],
  },
  {
    label: 'Extra',
    value: 'extra',
    items: [
      { label: 'EX1', value: 'EX1' },
      { label: 'EX2', value: 'EX2' },
      { label: 'EX3', value: 'EX3' },
    ],
  },
  {
    label: 'Starter Decks',
    value: 'starter',
    items: [
      { label: 'ST1', value: 'ST1' },
      { label: 'ST2', value: 'ST2' },
      { label: 'ST3', value: 'ST3' },
      { label: 'ST4', value: 'ST4' },
      { label: 'ST5', value: 'ST5' },
      { label: 'ST6', value: 'ST6' },
      { label: 'ST7', value: 'ST7' },
      { label: 'ST8', value: 'ST8' },
      { label: 'ST9', value: 'ST9' },
      { label: 'ST10', value: 'ST10' },
      { label: 'ST12', value: 'ST12' },
      { label: 'ST13', value: 'ST13' },
    ],
  },
];

export const CardTypes: string[] = ['Digi-Egg', 'Digimon', 'Tamer', 'Option'];

export const Keywords: string[] = [
  '\uff1cArmor Purge\uff1e',
  '\uff1cBlitz\uff1e',
  '\uff1cBlocker\uff1e',
  '\uff1cDecoy (Black)\uff1e',
  '\uff1cDecoy (Black/White)\uff1e',
  '\uff1cDecoy (Red)(Black)\uff1e',
  '\uff1cDecoy (D-Brigade)\uff1e',
  '\uff1cDe-Digivolve 1\uff1e',
  '\uff1cDe-Digivolve 2\uff1e',
  '\uff1cDe-Digivolve 3\uff1e',
  '\uff1cDe-Digivolve 4\uff1e',
  '\uff1cDelay\uff1e',
  '\uff1cDigi-Burst 1\uff1e',
  '\uff1cDigi-Burst 2\uff1e',
  '\uff1cDigi-Burst 3\uff1e',
  '\uff1cDigi-Burst 4\uff1e',
  '\uff1cDigi-Burst up to 4\uff1e',
  '\uff1cDigisorption -2\uff1e',
  '\uff1cDigisorption -3\uff1e',
  '\uff1cDigisorption\uff1e',
  '\uff1cDraw 1\uff1e',
  '\uff1cDraw 2\uff1e',
  '\uff1cDraw 3\uff1e',
  '\uff1cEvade\uff1e',
  '\uff1cJamming\uff1e',
  '\uff1cMaterial Save 1\uff1e',
  '\uff1cMaterial Save 2\uff1e',
  '\uff1cMaterial Save 3\uff1e',
  '\uff1cPiercing\uff1e',
  '\uff1cReboot\uff1e',
  '\uff1cRecovery +1 (Deck)\uff1e',
  '\uff1cRecovery +2 (Deck)\uff1e',
  '\uff1cRetaliation\uff1e',
  '\uff1cRush\uff1e',
  '\uff1cSave\uff1e',
  '\uff1cSecurity Attack +1\uff1e',
  '\uff1cSecurity Attack +2\uff1e',
  '\uff1cSecurity Attack -1\uff1e',
  '\uff1cSecurity Attack -2\uff1e',
  '\uff1cSecurity Attack -3\uff1e',
];

export const Colors: string[] = [
  'Red',
  'Blue',
  'Yellow',
  'Green',
  'Black',
  'Purple',
  'White',
  'Multi',
];

export const ColorsWithoutMulti: string[] = [
  'Red',
  'Blue',
  'Yellow',
  'Green',
  'Black',
  'Purple',
  'White',
];

export const Forms: string[] = [
  'In-Training',
  'Rookie',
  'Champion',
  'Ultimate',
  'Mega',
  'Hybrid',
  'Armor Form',
  'D-Reaper',
];

export const Attributes: string[] = [
  'Data',
  'Vaccine',
  'Virus',
  'Free',
  'Variable',
  'Unknown',
];

export const Types: string[] = [
  'Abnormal',
  'Alien Humanoid',
  'Amphibian',
  'Ancient Animal',
  'Ancient Bird',
  'Ancient Birdkin',
  'Ancient Dragon',
  'Ancient Dragonkin',
  'Ancient Fish',
  'Ancient Holy Warrior',
  'Ancient Insect',
  'Ancient Mineral',
  'Ancient Mythical Beast',
  'Ancient Plant',
  'Ancient',
  'Angel',
  'Ankylosaur',
  'Aquabeast',
  'Aquatic',
  'Archangel',
  'Armor',
  'Authority',
  'Avian',
  'Baby Dragon',
  'Beast Dragon',
  'Bagra Army',
  'Beast Knight',
  'Beast',
  'Beastkin',
  'Big Death-Stars',
  'Bird Dragon',
  'Bird',
  'Birdkin',
  'Blue Flare',
  'Boss',
  'Bulb',
  'CRT',
  'Carnivorous Plant',
  'Ceratopsian',
  'Cherub',
  'Composite',
  'Crustacean',
  'Cyborg',
  'D-Brigade',
  'Dark Animal',
  'Dark Dragon',
  'Dark Knight',
  'Demon Lord',
  'Demon',
  'Deva',
  'Dinosaur',
  'Dragon Warrior',
  'Dragon',
  'Dragonkin',
  'Earth Dragon',
  'Elusive Beast',
  'Evil Dragon',
  'Evil',
  'Fairy',
  'Fallen Angel',
  'Fire Dragon',
  'Flame',
  'Four Great Dragons',
  'Four Sovereigns',
  'Ghost',
  'Giant Bird',
  'General',
  'Holy Beast',
  'Holy Bird',
  'Holy Dragon',
  'Holy Sword',
  'Holy Warrior',
  'Ice-Snow',
  'Insectoid',
  'Invader',
  'Larva',
  'LCD',
  'Legend-Arms',
  'Lesser',
  'Light Dragon',
  'Machine Dragon',
  'Machine',
  'Magic Knight',
  'Magic Warrior',
  'Major',
  'Mammal',
  'Mine',
  'Mineral',
  'Mini Angel',
  'Mini Bird',
  'Mini Dragon',
  'Minor',
  'Mollusk',
  'Monk',
  'Musical Instrument',
  'Mutant',
  'Mysterious Beast',
  'Mysterious Bird',
  'Mythical Beast',
  'Mythical Dragon',
  'Olympos XII',
  'Perfect',
  'Plesiosaur',
  'Puppet',
  'Reptile',
  'Rock Dragon',
  'Rock',
  'Royal Knight',
  'Sea Animal',
  'Sea Beast',
  'Seraph',
  'Seven Great Demon Lords',
  'Shaman',
  'Sky Dragon',
  'Super Major',
  'Ten Warriors',
  'Three Great Angels',
  'Three Musketeers',
  'Throne',
  'Twilight',
  'Undead',
  'Unidentified',
  'Unique',
  'Unknown',
  'Vegetation',
  'Virtue',
  'Warrior',
  'Weapon',
  'Wizard',
  'X Antibody',
  'Xros Heart',
].sort();

export const Illustrators: string[] = [
  "As'Maria",
  'banira',
  'DAI-XT.',
  'GOSSAN',
  'Hisashi Fujiwara',
  'Hokyyuu',
  'Ishibashi Yosuke',
  'itohiro',
  'Kayo Horaguchi',
  'kaz',
  'Kazumasa Yasukuni',
  'Kenji Watanabe',
  'Kirita',
  'KISUKE',
  'koki',
  'MATSUMOTO EIGHT',
  'Minato Sashima',
  'Nakano Haito',
  'Naochika Morishita',
  'Okada Anmitsu',
  'p!k@ru',
  'Qacoro',
  'Ryodan',
  'Ryuda',
  'SENNSU',
  'Sanosuke Sakuma',
  'sasasi',
  'Shigeo Niwa',
  'Shin Sasaki',
  'TANIMESO',
  'TSCR',
  'Takase',
  'Takumi Kousaka',
  'Teppei Tadokoro',
  'Tomotake Kinoshita',
  'Tonamikanji',
  'Tsunemi Aosa',
  'tyuga',
  'UnnoDaisuke',
  'funbolt',
  'satsuki may',
  'shosuke',
  'sunohara',
  'tessy',
  'toriyufu',
  'yuuki.',
].sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()));

export const Lvs: string[] = ['Lv.2', 'Lv.3', 'Lv.4', 'Lv.5', 'Lv.6', 'Lv.7'];

export const Rarities: string[] = ['C', 'U', 'R', 'SR', 'SEC', 'P'];

export const Versions: string[] = ['Normal', 'AA', 'Stamp', 'Pre-Release'];

export const SpecialRequirements: string[] = [
  'Digivolve',
  'DNA Digivolution',
  'DigiXros',
];

export const Restrictions: string[] = ['Banned', 'Restricted to 1'];

export const Blocks: string[] = ['00', '01', '02'];
