export const GroupedSets = [
  {
    label: 'Standard', value: 'displays',
    items: [
      {label: 'BT1', value: 'BT1'},
      {label: 'BT2', value: 'BT2'},
      {label: 'BT3', value: 'BT3'},
      {label: 'BT4', value: 'BT4'},
      {label: 'BT5', value: 'BT5'},
      {label: 'BT6', value: 'BT6'},
      {label: 'BT7', value: 'BT7'},
      {label: 'BT8', value: 'BT8'},
      {label: 'BT9', value: 'BT9'}
    ]
  },
  {
    label: 'Extra', value: 'extra',
    items: [
      {label: 'EX1', value: 'EX1'},
      {label: 'EX2', value: 'EX2'}
    ]
  },
  {
    label: 'Starter Decks', value: 'starter',
    items: [
      {label: 'ST01', value: 'ST01'},
      {label: 'ST02', value: 'ST02'},
      {label: 'ST03', value: 'ST03'},
      {label: 'ST04', value: 'ST04'},
      {label: 'ST05', value: 'ST05'},
      {label: 'ST06', value: 'ST06'},
      {label: 'ST07', value: 'ST07'},
      {label: 'ST08', value: 'ST08'},
      {label: 'ST09', value: 'ST09'},
      {label: 'ST10', value: 'ST10'},
      {label: 'ST12', value: 'ST12'},
      {label: 'ST13', value: 'ST13'}
    ]
  }
];

export const CardTypes: string[] = ['Digi-Egg', 'Digimon', 'Tamer', 'Option'];

export const Keywords: string[] = [
  'Digivolve: ',
  '\uff1cDraw 1\uff1e',
  '\uff1cDraw 2\uff1e',
  '\uff1cDraw 3\uff1e',
  '\uff1cPiercing\uff1e',
  '\uff1cJamming\uff1e',
  '\uff1cRecovery +1 (Deck)\uff1e',
  '\uff1cRecovery +2 (Deck)\uff1e',
  '\uff1cSecurity Attack +1\uff1e',
  '\uff1cSecurity Attack +2\uff1e',
  '\uff1cSecurity Attack -1\uff1e',
  '\uff1cSecurity Attack -2\uff1e',
  '\uff1cSecurity Attack -3\uff1e',
  '\uff1cReboot\uff1e',
  '\uff1cDigisorption\uff1e',
  '\uff1cDigisorption -2\uff1e',
  '\uff1cDigisorption -3\uff1e',
  '\uff1cDe-Digivolve 1\uff1e',
  '\uff1cDe-Digivolve 2\uff1e',
  '\uff1cDe-Digivolve 3\uff1e',
  '\uff1cDe-Digivolve 4\uff1e',
  '\uff1cDigi-Burst 1\uff1e',
  '\uff1cDigi-Burst 2\uff1e',
  '\uff1cDigi-Burst 3\uff1e',
  '\uff1cDigi-Burst 4\uff1e',
  '\uff1cDigi-Burst up to 4\uff1e',
  '\uff1cRush\uff1e',
  '\uff1cBlitz\uff1e',
  '\uff1cDelay\uff1e',
  '\uff1cDecoy (Black)\uff1e',
  '\uff1cDecoy (Black/White)\uff1e',
  '\uff1cDecoy (Red)(Black)\uff1e',
  '\uff1cRetaliation\uff1e',
  '\uff1cArmor Purge\uff1e'
];

export const Colors: string[] = ['Red', 'Blue', 'Yellow', 'Green', 'Black', 'Purple', 'White', 'Multi'];

export const Forms: string[] = ["In-Training", "Rookie", "Champion", "Ultimate", "Mega", "Hybrid", "Armor Form", "D-Reaper"];

export const Attributes: string[] = ['Data', 'Vaccine', 'Virus', 'Free', 'Variable', 'Unknown'];

export const Types: string[] = [
  "Abnormal",
  "Amphibian",
  "Ancient Animal",
  "Ancient Bird",
  "Ancient Birdkin",
  "Ancient Dragon",
  "Ancient Dragonkin",
  "Ancient Fish",
  "Ancient Holy Warrior",
  "Ancient Insect",
  "Ancient Mineral",
  "Ancient Mythical Beast",
  "Ancient Plant",
  "Ancient",
  "Angel",
  "Ankylosaur",
  "Aquabeast",
  "Aquatic",
  "Archangel",
  "Armor",
  "Armor",
  "Authority",
  "Avian",
  "Baby Dragon",
  "Beast Dragon",
  "Beast Knight",
  "Beast",
  "Beast",
  "Beastkin",
  "Big Death-Stars",
  "Bird Dragon",
  "Bird",
  "Birdkin",
  "Boss",
  "Boss",
  "Bulb",
  "CRT",
  "Carnivorous Plant",
  "Ceratopsian",
  "Cherub",
  "Composite",
  "Crustacean",
  "Cyborg",
  "D-Brigade",
  "Dark Animal",
  "Dark Dragon",
  "Dark Knight",
  "Demon Lord",
  "Demon",
  "Deva",
  "Dinosaur",
  "Dinosaur",
  "Dragon Warrior",
  "Dragon",
  "Dragonkin",
  "Earth Dragon",
  "Elusive Beast",
  "Evil Dragon",
  "Evil Dragon",
  "Evil",
  "Fairy",
  "Fallen Angel",
  "Fire Dragon",
  "Flame",
  "Four Great Dragons",
  "Four Sovereigns",
  "Ghost",
  "Giant Bird",
  "Holy Beast",
  "Holy Bird",
  "Holy Dragon",
  "Holy Sword",
  "Holy Warrior",
  "Ice-Snow",
  "Insectoid",
  "Invader",
  "Larva",
  "Legend-Arms",
  "Lesser",
  "Lesser",
  "Light Dragon",
  "Machine Dragon",
  "Machine",
  "Machine",
  "Magic Knight",
  "Magic Warrior",
  "Major",
  "Mammal",
  "Mine",
  "Mineral",
  "Mini Angel",
  "Mini Bird",
  "Mini Dragon",
  "Minor",
  "Mollusk",
  "Mutant",
  "Mutant",
  "Mysterious Beast",
  "Mysterious Bird",
  "Mythical Beast",
  "Mythical Dragon",
  "Olympos XII",
  "Perfect",
  "Plesiosaur",
  "Puppet",
  "Reptile",
  "Rock Dragon",
  "Rock",
  "Royal Knight",
  "Sea Animal",
  "Sea Beast",
  "Seraph",
  "Seven Great Demon Lords",
  "Shaman",
  "Sky Dragon",
  "Super Major",
  "Ten Warriors",
  "Three Great Angels",
  "Three Musketeers",
  "Throne",
  "Undead",
  "Unidentified",
  "Unique",
  "Unknown",
  "Vegetation",
  "Virtue",
  "Warrior",
  "Weapon",
  "Wizard",
  "X-Antibody",
  "X Antibody"
].sort();

export const Lvs: string[] = ['Lv.2', 'Lv.3', 'Lv.4', 'Lv.5', 'Lv.6', 'Lv.7'];

export const Rarities: string[] = ['P', 'C', 'U', 'R', 'SR', 'SEC'];

export const Versions: string[] = ['Normal', 'AA', 'Stamp', 'Pre-Release'];
