export const GroupedSets = [
  {
    label: 'Standard', value: 'displays',
    items: [
      {label: 'BT1', value: 'BT1'},
      {label: 'BT2', value: 'BT2'},
      {label: 'BT3', value: 'BT3'},
      {label: 'BT4', value: 'BT4'},
      {label: 'BT5', value: 'BT5'},
      {label: 'BT6', value: 'BT6'},
      {label: 'BT7', value: 'BT7'},
      {label: 'BT8', value: 'BT8'},
      {label: 'BT9', value: 'BT9'}
    ]
  },
  {
    label: 'Extra', value: 'extra',
    items: [
      {label: 'EX1', value: 'EX1'},
      {label: 'EX2', value: 'EX2'}
    ]
  },
  {
    label: 'Starter Decks', value: 'starter',
    items: [
      {label: 'ST01', value: 'ST01'},
      {label: 'ST02', value: 'ST02'},
      {label: 'ST03', value: 'ST03'},
      {label: 'ST04', value: 'ST04'},
      {label: 'ST05', value: 'ST05'},
      {label: 'ST06', value: 'ST06'},
      {label: 'ST07', value: 'ST07'},
      {label: 'ST08', value: 'ST08'},
      {label: 'ST09', value: 'ST09'},
      {label: 'ST10', value: 'ST10'},
      {label: 'ST12', value: 'ST12'},
      {label: 'ST13', value: 'ST13'}
    ]
  }
];

export const CardTypes: string[] = ['Digi-Egg', 'Digimon', 'Tamer', 'Option'];

export const Colors: string[] = ['Red', 'Blue', 'Yellow', 'Green', 'Black', 'Purple', 'White', 'Multi'];

export const Forms: string[] = ["In-Training", "Rookie", "Champion", "Ultimate", "Mega", "Hybrid", "Armor Form"];

export const Attributes: string[] = ['Data', 'Vaccine', 'Virus', 'Free', 'Variable'];

export const Types: string[] = [
  "Bulb",
  "Baby Dragon",
  "Amphibian",
  "Lesser",
  "Mini Angel",
  "Unidentified",
  "Mini Dragon",
  "Reptile",
  "Dinosaur",
  "Bird",
  "Avian",
  "Giant Bird",
  "Fire Dragon",
  "Earth Dragon",
  "Cyborg",
  "Birdkin",
  "Undead",
  "Dragonkin",
  "Machine Dragon",
  "Mammal",
  "Sea Beast",
  "Beast",
  "Ice-Snow",
  "Sea Animal",
  "Beastkin",
  "Puppet",
  "Dark Animal",
  "Machine",
  "Ancient Animal",
  "Holy Beast",
  "Fairy",
  "Angel",
  "Shaman",
  "Archangel",
  "Magic Warrior",
  "Authority",
  "Seraph",
  "Demon",
  "Vegetation",
  "Insectoid",
  "Carnivorous Plant",
  "Perfect",
  "Royal Knight",
  "Mythical Dragon",
  "Dark Dragon",
  "Four Great Dragons",
  "Rock",
  "Mollusk",
  "Evil",
  "Wizard",
  "Fallen Angel",
  "Composite",
  "Seven Great Demon Lords",
  "Evil Dragon",
  "-",
  "Mutant",
  "Mini Bird",
  "Larva",
  "Armor",
  "Flame",
  "Rock Dragon",
  "Holy Dragon",
  "Three Great Angels",
  "Thron",
  "Light Dragon",
  "Legend-Arms",
  "Holy Sword",
  "Warrior",
  "Unique",
  "Mythical Beast",
  "Ancient Dragon",
  "Ankylosaur",
  "Cherub",
  "Virtue",
  "Olympos XII",
  "Boss",
  "D-Brigade",
  "Armor/Legend-Arms",
  "Abnormal",
  "Mine",
  "Beast Knight",
  "Demon Lord",
  "Holy Warrior",
  "Weapon",
  "Dragon",
  "Crustacean",
  "Ancient Bird",
  "Unknown",
  "Mysterious Bird",
  "Throne",
  "Holy Bird",
  "Mineral",
  "Machine",
  "Ghost",
  "Ten Warriors",
  "Minor",
  "Ceratopsian",
  "Big Death-Stars",
  "Ancient Fish",
  "Aquabeast",
  "Magic Knight",
  "Major",
  "Mysterious Beast",
  "Super Major",
  "Ancient",
  "Boss",
  "CRT",
  "Deva",
  "Dark Knight",
  "Evil Dragon",
  "X-Antibody",
  "Three Musketeers",
  "Elusive Beast",
  "Four Sovereigns",
  "Ancient Plant",
  "Invader",
  "Lesser",
  "Plesiosaur",
  "Dragon Warrior",
  "Ancient Birdkin",
  "Mutant",
  "Dinosaur",
  "Ancient Insect",
  "Beast",
  "Beast Dragon",
  "Ancient Mineral",
  "Ancient Mythical Beast",
  "Ancient Dragonkin",
  "Ancient Holy Warrior",
  "Bird Dragon",
  "Sky Dragon"
].sort();

export const Lvs: string[] = ['Lv.2', 'Lv.3', 'Lv.4', 'Lv.5', 'Lv.6', 'Lv.7'];

export const Rarities: string[] = ['P', 'C', 'U', 'R', 'SR', 'SEC'];

export const Versions: string[] = ['Normal', 'AA', 'Stamp', 'Pre-Release'];
