import {ICard} from "../models";

export const ST06CardList: ICard[] = [
  {"id": "ST6-01", "name": "Pagumon", "cardImage": "assets/images/cards/ST6-01.png", "cardType": "Digi-Egg", "dp": "-", "playCost": "-", "digivolveCost1": "-", "digivolveCost2": "-", "cardLv": "Lv.2", "form": "In-Training", "attribute": "-", "type": "Lesser", "rarity": "U", "cardNumber": "ST6-01", "effect": "-", "digivolveEffect": "[On Deletion] Trash the top 2 cards of your deck.", "securityEffect": "-", "notes": "\u25b9Starter Deck, VENOMOUS VIOLET[ST-6]", "color": "Purple", "version": "Normal"},
  {"id": "ST6-02", "name": "DemiDevimon", "cardImage": "assets/images/cards/ST6-02.png", "cardType": "Digimon", "dp": "4000", "playCost": "2", "digivolveCost1": "1 from Lv.2", "digivolveCost2": "-", "cardLv": "Lv.3", "form": "Rookie", "attribute": "Virus", "type": "Evil", "rarity": "C", "cardNumber": "ST6-02", "effect": "-", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, VENOMOUS VIOLET[ST-6]", "color": "Purple", "version": "Normal"},
  {"id": "ST6-03", "name": "Gabumon", "cardImage": "assets/images/cards/ST6-03.png", "cardType": "Digimon", "dp": "2000", "playCost": "3", "digivolveCost1": "0 from Lv.2", "digivolveCost2": "-", "cardLv": "Lv.3", "form": "Rookie", "attribute": "Data", "type": "Reptile", "rarity": "C", "cardNumber": "ST6-03", "effect": "-", "digivolveEffect": "[When Attacking] Trigger \uff1cDraw 1\uff1e. (Draw 1 card from your deck.) Then, trash 1 card in your hand.", "securityEffect": "-", "notes": "\u25b9Starter Deck, VENOMOUS VIOLET[ST-6]", "color": "Purple", "version": "Normal"},
  {"id": "ST6-04", "name": "Dracmon", "cardImage": "assets/images/cards/ST6-04.png", "cardType": "Digimon", "dp": "2000", "playCost": "3", "digivolveCost1": "0 from Lv.2", "digivolveCost2": "-", "cardLv": "Lv.3", "form": "Rookie", "attribute": "Virus", "type": "Undead", "rarity": "U", "cardNumber": "ST6-04", "effect": "[On Play] You may return 1 purple Option card with a memory cost of 1 or 7 from your trash to your hand.", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, VENOMOUS VIOLET[ST-6]", "color": "Purple", "version": "Normal"},
  {"id": "ST6-05", "name": "Elecmon", "cardImage": "assets/images/cards/ST6-05.png", "cardType": "Digimon", "dp": "5000", "playCost": "4", "digivolveCost1": "0 from Lv.2", "digivolveCost2": "-", "cardLv": "Lv.3", "form": "Rookie", "attribute": "Virus", "type": "Mammal", "rarity": "C", "cardNumber": "ST6-05", "effect": "-", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, VENOMOUS VIOLET[ST-6]", "color": "Purple", "version": "Normal"},
  {"id": "ST6-06", "name": "Garurumon", "cardImage": "assets/images/cards/ST6-06.png", "cardType": "Digimon", "dp": "4000", "playCost": "4", "digivolveCost1": "2 from Lv.3", "digivolveCost2": "-", "cardLv": "Lv.4", "form": "Champion", "attribute": "Virus", "type": "Beast", "rarity": "C", "cardNumber": "ST6-06", "effect": "-", "digivolveEffect": "[When Attacking] Trigger \uff1cDraw 1\uff1e. (Draw 1 card from your deck.) Then, trash 1 card in your hand.", "securityEffect": "-", "notes": "\u25b9Starter Deck, VENOMOUS VIOLET[ST-6]", "color": "Purple", "version": "Normal"},
  {"id": "ST6-07", "name": "Youkomon", "cardImage": "assets/images/cards/ST6-07.png", "cardType": "Digimon", "dp": "6000", "playCost": "5", "digivolveCost1": "2 from Lv.3", "digivolveCost2": "-", "cardLv": "Lv.4", "form": "Champion", "attribute": "Data", "type": "Mysterious Beast", "rarity": "C", "cardNumber": "ST6-07", "effect": "-", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, VENOMOUS VIOLET[ST-6]", "color": "Purple", "version": "Normal"},
  {"id": "ST6-08", "name": "Devimon", "cardImage": "assets/images/cards/ST6-08.png", "cardType": "Digimon", "dp": "5000", "playCost": "6", "digivolveCost1": "1 from Lv.3", "digivolveCost2": "-", "cardLv": "Lv.4", "form": "Champion", "attribute": "Virus", "type": "Fallen Angel", "rarity": "U", "cardNumber": "ST6-08", "effect": "\uff1cBlocker\uff1e (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)[When Attacking] Lose 2 memory.", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, VENOMOUS VIOLET[ST-6]", "color": "Purple", "version": "Normal"},
  {"id": "ST6-08_P1", "name": "Devimon", "cardImage": "assets/images/cards/ST6-08_P1.png", "cardType": "Digimon", "dp": "5000", "playCost": "6", "digivolveCost1": "1 from Lv.3", "digivolveCost2": "-", "cardLv": "Lv.4", "form": "Champion", "attribute": "Virus", "type": "Fallen Angel", "rarity": "U", "cardNumber": "ST6-08", "effect": "\uff1cBlocker\uff1e (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)[When Attacking] Lose 2 memory.", "digivolveEffect": "-", "securityEffect": "-", "notes": "2021 Online Regionals Participant Pack", "color": "Purple", "version": "Stamp"},
  {"id": "ST6-08_P2", "name": "Devimon", "cardImage": "assets/images/cards/ST6-08_P2.png", "cardType": "Digimon", "dp": "5000", "playCost": "6", "digivolveCost1": "1 from Lv.3", "digivolveCost2": "-", "cardLv": "Lv.4", "form": "Champion", "attribute": "Virus", "type": "Fallen Angel", "rarity": "U", "cardNumber": "ST6-08", "effect": "\uff1cBlocker\uff1e (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)[When Attacking] Lose 2 memory.", "digivolveEffect": "-", "securityEffect": "-", "notes": "2021 Finalist Card Set", "color": "Purple", "version": "Stamp"},
  {"id": "ST6-08_P3", "name": "Devimon", "cardImage": "assets/images/cards/ST6-08_P3.png", "cardType": "Digimon", "dp": "5000", "playCost": "6", "digivolveCost1": "1 from Lv.3", "digivolveCost2": "-", "cardLv": "Lv.4", "form": "Champion", "attribute": "Virus", "type": "Fallen Angel", "rarity": "U", "cardNumber": "ST6-08", "effect": "\uff1cBlocker\uff1e (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)[When Attacking] Lose 2 memory.", "digivolveEffect": "-", "securityEffect": "-", "notes": "2021 Champion Card Set", "color": "Purple", "version": "Stamp"},
  {"id": "ST6-08_P4", "name": "Devimon", "cardImage": "assets/images/cards/ST6-08_P4.png", "cardType": "Digimon", "dp": "5000", "playCost": "6", "digivolveCost1": "1 from Lv.3", "digivolveCost2": "-", "cardLv": "Lv.4", "form": "Champion", "attribute": "Virus", "type": "Fallen Angel", "rarity": "U", "cardNumber": "ST6-08", "effect": "\uff1cBlocker\uff1e (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)[When Attacking] Lose 2 memory.", "digivolveEffect": "-", "securityEffect": "-", "notes": "Judge Pack", "color": "Purple", "version": "Stamp"},
  {"id": "ST6-09", "name": "Kyukimon", "cardImage": "assets/images/cards/ST6-09.png", "cardType": "Digimon", "dp": "9000", "playCost": "6", "digivolveCost1": "3 from Lv.4", "digivolveCost2": "-", "cardLv": "Lv.5", "form": "Ultimate", "attribute": "Virus", "type": "Mysterious Beast", "rarity": "C", "cardNumber": "ST6-09", "effect": "-", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, VENOMOUS VIOLET[ST-6]", "color": "Purple", "version": "Normal"},
  {"id": "ST6-10", "name": "SkullSatamon", "cardImage": "assets/images/cards/ST6-10.png", "cardType": "Digimon", "dp": "7000", "playCost": "6", "digivolveCost1": "3 from Lv.4", "digivolveCost2": "-", "cardLv": "Lv.5", "form": "Ultimate", "attribute": "Virus", "type": "Undead", "rarity": "U", "cardNumber": "ST6-10", "effect": "[When Digivolving] You may return 1 purple Digimon card from your trash to your hand.", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, VENOMOUS VIOLET[ST-6]", "color": "Purple", "version": "Normal"},
  {"id": "ST6-11", "name": "WereGarurumon", "cardImage": "assets/images/cards/ST6-11.png", "cardType": "Digimon", "dp": "7000", "playCost": "7", "digivolveCost1": "3 from Lv.4", "digivolveCost2": "-", "cardLv": "Lv.5", "form": "Ultimate", "attribute": "Virus", "type": "Beastkin", "rarity": "R", "cardNumber": "ST6-11", "effect": "-", "digivolveEffect": "[Your Turn] While there are 5 or more cards in your trash, this Digimon gets +2000 DP.", "securityEffect": "-", "notes": "\u25b9Starter Deck, VENOMOUS VIOLET[ST-6]", "color": "Purple", "version": "Normal"},
  {"id": "ST6-12", "name": "VenomMyotismon", "cardImage": "assets/images/cards/ST6-12.png", "cardType": "Digimon", "dp": "11000", "playCost": "10", "digivolveCost1": "3 from Lv.5", "digivolveCost2": "-", "cardLv": "Lv.6", "form": "Mega", "attribute": "Virus", "type": "Dark Animal", "rarity": "R", "cardNumber": "ST6-12", "effect": "[When Digivolving] Up to 2 of your Digimon gain \uff1cRetaliation\uff1e (When this Digimon is deleted after losing a battle, delete the Digimon it was battling) until the end of your opponent's next turn.", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, VENOMOUS VIOLET[ST-6]", "color": "Purple", "version": "Normal"},
  {"id": "ST6-13", "name": "CresGarurumon", "cardImage": "assets/images/cards/ST6-13.png", "cardType": "Digimon", "dp": "12000", "playCost": "12", "digivolveCost1": "4 from Lv.5", "digivolveCost2": "-", "cardLv": "Lv.6", "form": "Mega", "attribute": "Data", "type": "Beast Knight", "rarity": "SR", "cardNumber": "ST6-13", "effect": "\uff1cSecurity Attack +1\uff1e (This Digimon checks 1 additional security card.)[Main] \uff1cDigi-Burst 2\uff1e (Trash 2 of this Digimon's Digivolution cards to activate the effect below.)\u30fbPlay 1 purple level 3 Digimon card from your trash without paying its memory cost.", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, VENOMOUS VIOLET[ST-6]", "color": "Purple", "version": "Normal"},
  {"id": "ST6-14", "name": "Matt Ishida", "cardImage": "assets/images/cards/ST6-14.png", "cardType": "Tamer", "dp": "-", "playCost": "2", "digivolveCost1": "-", "digivolveCost2": "-", "cardLv": "", "form": "-", "attribute": "-", "type": "-", "rarity": "R", "cardNumber": "ST6-14", "effect": "[Your Turn] When one of your Digimon is deleted, you may suspend this Tamer to gain 1 memory.", "digivolveEffect": "-", "securityEffect": "[Security] Play this card without paying its memory cost.", "notes": "\u25b9Starter Deck, VENOMOUS VIOLET[ST-6]", "color": "Purple", "version": "Normal"},
  {"id": "ST6-15", "name": "Death Claw", "cardImage": "assets/images/cards/ST6-15.png", "cardType": "Option", "dp": "-", "playCost": "1", "digivolveCost1": "-", "digivolveCost2": "-", "cardLv": "", "form": "-", "attribute": "-", "type": "-", "rarity": "C", "cardNumber": "ST6-15", "effect": "[Main] You may delete 1 of your Digimon to delete 1 of your opponent's level 4 or lower Digimon.", "digivolveEffect": "-", "securityEffect": "[Security] Delete 1 of your opponent's level 4 or lower Digimon.", "notes": "\u25b9Starter Deck, VENOMOUS VIOLET[ST-6]", "color": "Purple", "version": "Normal"},
  {"id": "ST6-16", "name": "Nail Bone", "cardImage": "assets/images/cards/ST6-16.png", "cardType": "Option", "dp": "-", "playCost": "7", "digivolveCost1": "-", "digivolveCost2": "-", "cardLv": "", "form": "-", "attribute": "-", "type": "-", "rarity": "U", "cardNumber": "ST6-16", "effect": "[Main] You may play 1 purple level 3 Digimon card and 1 purple level 4 Digimon card from your trash without paying their memory costs. Any [On Play] effects on Digimon played with this effect don't activate.", "digivolveEffect": "-", "securityEffect": "[Security] You may play 1 purple level 4 or lower Digimon card from your trash without paying its memory cost. Any [On Play] effects on Digimon played with this effect don't activate.", "notes": "\u25b9Starter Deck, VENOMOUS VIOLET[ST-6]", "color": "Purple", "version": "Normal"}
];
