export const ColorMap = new Map<string, string>([
  ['Red', '#e7002c'],
  ['Blue', '#0097e1'],
  ['Yellow', '#fee100'],
  ['Green', '#009c6b'],
  ['Black', '#808080'],
  ['Purple', '#6555a2'],
  ['White', '#ffffff'],

  ['Red/Blue', '#e7002c'],
  ['Red/Yellow', '#e7002c'],
  ['Red/Green', '#e7002c'],
  ['Red/Black', '#e7002c'],
  ['Red/Purple', '#e7002c'],
  ['Red/White', '#e7002c'],

  ['Blue/Red', '#0097e1'],
  ['Blue/Yellow', '#0097e1'],
  ['Blue/Green', '#0097e1'],
  ['Blue/Black', '#0097e1'],
  ['Blue/Purple', '#0097e1'],
  ['Blue/White', '#0097e1'],

  ['Yellow/Red', '#fee100'],
  ['Yellow/Blue', '#fee100'],
  ['Yellow/Green', '#fee100'],
  ['Yellow/Black', '#fee100'],
  ['Yellow/Purple', '#fee100'],
  ['Yellow/White', '#fee100'],

  ['Green/Red', '#009c6b'],
  ['Green/Blue', '#009c6b'],
  ['Green/Yellow', '#009c6b'],
  ['Green/Black', '#009c6b'],
  ['Green/Purple', '#009c6b'],
  ['Green/White', '#009c6b'],

  ['Black/Red', '#808080'],
  ['Black/Blue', '#808080'],
  ['Black/Yellow', '#808080'],
  ['Black/Green', '#808080'],
  ['Black/Purple', '#808080'],
  ['Black/White', '#808080'],

  ['Purple/Red', '#6555a2'],
  ['Purple/Blue', '#6555a2'],
  ['Purple/Yellow', '#6555a2'],
  ['Purple/Green', '#6555a2'],
  ['Purple/Black', '#6555a2'],
  ['Purple/White', '#6555a2'],
]);

export const DeckColorMap = new Map<string, any>([
  ['Red', { name: 'Red', img: 'assets/decks/red.svg' }],
  ['Blue', { name: 'Blue', img: 'assets/decks/blue.svg' }],
  ['Yellow', { name: 'Yellow', img: 'assets/decks/yellow.svg' }],
  ['Green', { name: 'Green', img: 'assets/decks/green.svg' }],
  ['Black', { name: 'Black', img: 'assets/decks/black.svg' }],
  ['Purple', { name: 'Purple', img: 'assets/decks/purple.svg' }],
  ['White', { name: 'White', img: 'assets/decks/white.svg' }],
]);

export const ColorOrderMap = new Map<string, number>([
  ['Red', 0],
  ['Red/Blue', 1],
  ['Red/Yellow', 2],
  ['Red/Green', 3],
  ['Red/Black', 4],
  ['Red/Purple', 5],
  ['Blue', 6],
  ['Blue/Red', 7],
  ['Blue/Yellow', 8],
  ['Blue/Green', 9],
  ['Blue/Black', 10],
  ['Blue/Purple', 11],
  ['Yellow', 12],
  ['Yellow/Red', 13],
  ['Yellow/Blue', 14],
  ['Yellow/Green', 15],
  ['Yellow/Black', 16],
  ['Yellow/Purple', 17],
  ['Green', 18],
  ['Green/Red', 19],
  ['Green/Blue', 20],
  ['Green/Yellow', 21],
  ['Green/Black', 22],
  ['Green/Purple', 23],
  ['Black', 24],
  ['Black/Red', 25],
  ['Black/Blue', 26],
  ['Black/Yellow', 27],
  ['Black/Green', 28],
  ['Black/Purple', 29],
  ['Purple', 30],
  ['Purple/Red', 31],
  ['Purple/Blue', 32],
  ['Purple/Yellow', 33],
  ['Purple/Green', 34],
  ['Purple/Black', 35],
  ['White', 36],
  ['Multi', 37],
]);
