export const COLORS = [
  'Red',
  'Blue',
  'Yellow',
  'Green',
  'Black',
  'Purple',
  'White',
  'Multi',

  'Red/Blue',
  'Red/Yellow',
  'Red/Green',
  'Red/Black',
  'Red/Purple',

  'Blue/Red',
  'Blue/Yellow',
  'Blue/Green',
  'Blue/Black',
  'Blue/Purple',

  'Yellow/Red',
  'Yellow/Blue',
  'Yellow/Green',
  'Yellow/Black',
  'Yellow/Purple',

  'Green/Red',
  'Green/Blue',
  'Green/Yellow',
  'Green/Black',
  'Green/Purple',

  'Black/Red',
  'Black/Blue',
  'Black/Yellow',
  'Black/Green',
  'Black/Purple',

  'Purple/Red',
  'Purple/Blue',
  'Purple/Yellow',
  'Purple/Green',
  'Purple/Black',
];

export const ColorOrderMap = new Map<string, number>([
  ['Red', 0],
  ['Red/Blue', 1],
  ['Red/Yellow', 2],
  ['Red/Green', 3],
  ['Red/Black', 4],
  ['Red/Purple', 5],
  ['Blue', 6],
  ['Blue/Red', 7],
  ['Blue/Yellow', 8],
  ['Blue/Green', 9],
  ['Blue/Black', 10],
  ['Blue/Purple', 11],
  ['Yellow', 12],
  ['Yellow/Red', 13],
  ['Yellow/Blue', 14],
  ['Yellow/Green', 15],
  ['Yellow/Black', 16],
  ['Yellow/Purple', 17],
  ['Green', 18],
  ['Green/Red', 19],
  ['Green/Blue', 20],
  ['Green/Yellow', 21],
  ['Green/Black', 22],
  ['Green/Purple', 23],
  ['Black', 24],
  ['Black/Red', 25],
  ['Black/Blue', 26],
  ['Black/Yellow', 27],
  ['Black/Green', 28],
  ['Black/Purple', 29],
  ['Purple', 30],
  ['Purple/Red', 31],
  ['Purple/Blue', 32],
  ['Purple/Yellow', 33],
  ['Purple/Green', 34],
  ['Purple/Black', 35],
  ['White', 36],
  ['Multi', 37]
]);

export const ColorList = [
  {name: 'Red', img: 'assets/decks/red.svg'},
  {name: 'Blue', img: 'assets/decks/blue.svg'},
  {name: 'Yellow', img: 'assets/decks/yellow.svg'},
  {name: 'Green', img: 'assets/decks/green.svg'},
  {name: 'Black', img: 'assets/decks/black.svg'},
  {name: 'Purple', img: 'assets/decks/purple.svg'},
  {name: 'White', img: 'assets/decks/white.svg'}
];
