import { ITag } from "./interfaces/tag.interface";

export const TAGS = [
  'BT1',
  'BT2',
  'BT3',
  'BT4',
  'BT5',
  'BT6',
  'BT7',
  'BT8',
  'BT9',
  'BT10',
  'EX1',
  'EX2',
  'EX3',
  'ST1',
  'ST2',
  'ST3',
  'ST4',
  'ST5',
  'ST6',
  'ST7',
  'ST8',
  'ST9',
  'ST10',
  'ST12',
  'ST13',
  'Tournament',
  'Casual',
];

export const tagsList: ITag[] = [
  { name: 'BT1', color: 'Primary' },
  { name: 'BT2', color: 'Primary' },
  { name: 'BT3', color: 'Primary' },
  { name: 'BT4', color: 'Primary' },
  { name: 'BT5', color: 'Primary' },
  { name: 'BT6', color: 'Primary' },
  { name: 'BT7', color: 'Primary' },
  { name: 'BT8', color: 'Primary' },
  { name: 'BT9', color: 'Primary' },
  { name: 'BT10', color: 'Primary' },
  { name: 'BT11', color: 'Primary' },

  { name: 'EX1', color: 'Primary' },
  { name: 'EX2', color: 'Primary' },
  { name: 'EX3', color: 'Primary' },

  { name: 'ST1', color: 'Primary' },
  { name: 'ST2', color: 'Primary' },
  { name: 'ST3', color: 'Primary' },
  { name: 'ST4', color: 'Primary' },
  { name: 'ST5', color: 'Primary' },
  { name: 'ST6', color: 'Primary' },
  { name: 'ST7', color: 'Primary' },
  { name: 'ST8', color: 'Primary' },
  { name: 'ST9', color: 'Primary' },
  { name: 'ST10', color: 'Primary' },
  { name: 'ST11', color: 'Primary' },
  { name: 'ST12', color: 'Primary' },
  { name: 'ST13', color: 'Primary' },

  { name: 'Tournament', color: 'Primary' },
  { name: 'Casual', color: 'Primary' },

  { name: '1th Place', color: 'Primary' },
  { name: '2nd Place', color: 'Primary' },
  { name: '3rd Place', color: 'Primary' },

  { name: 'Illegal', color: 'Primary' },
];
