import {ICard} from "../../app/models";

export const ST04CardList: ICard[] = [
  {"id": "ST4-01", "name": "Motimon", "cardImage": "./assets/images/cards/ST4-01.png", "cardType": "Digi-Egg", "dp": "-", "playCost": "-", "digivolveCost1": "-", "digivolveCost2": "-", "cardLv": "Lv.2", "form": "In-Training", "attribute": "-", "type": "Lesser", "rarity": "U", "cardNumber": "ST4-01", "effect": "-", "digivolveEffect": "[Your Turn] While this Digimon is level 6 or higher, it gets +1000 DP.", "securityEffect": "-", "notes": "\u25b9Starter Deck, GIGA GREEN[ST-4]", "color": "Green", "version": "Normal"},
  {"id": "ST4-02", "name": "Floramon", "cardImage": "./assets/images/cards/ST4-02.png", "cardType": "Digimon", "dp": "4000", "playCost": "2", "digivolveCost1": "1 from Lv.2", "digivolveCost2": "-", "cardLv": "Lv.3", "form": "Rookie", "attribute": "Data", "type": "Vegetation", "rarity": "C", "cardNumber": "ST4-02", "effect": "-", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, GIGA GREEN[ST-4]", "color": "Green", "version": "Normal"},
  {"id": "ST4-03", "name": "Tentomon", "cardImage": "./assets/images/cards/ST4-03.png", "cardType": "Digimon", "dp": "2000", "playCost": "3", "digivolveCost1": "0 from Lv.2", "digivolveCost2": "-", "cardLv": "Lv.3", "form": "Rookie", "attribute": "Vaccine", "type": "Insectoid", "rarity": "U", "cardNumber": "ST4-03", "effect": "[On Play] Reveal the top card of your deck. If it's a green Digimon card, add it to your hand. Otherwise, place it at the bottom of your deck.", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, GIGA GREEN[ST-4]", "color": "Green", "version": "Normal"},
  {"id": "ST4-03_P1", "name": "Tentomon", "cardImage": "./assets/images/cards/ST4-03_P1.png", "cardType": "Digimon", "dp": "2000", "playCost": "3", "digivolveCost1": "0 from Lv.2", "digivolveCost2": "-", "cardLv": "Lv.3", "form": "Rookie", "attribute": "Vaccine", "type": "Insectoid", "rarity": "U", "cardNumber": "ST4-03", "effect": "[On Play] Reveal the top card of your deck. If it's a green Digimon card, add it to your hand. Otherwise, place it at the bottom of your deck.", "digivolveEffect": "-", "securityEffect": "-", "notes": "Official Tournament Pack Vol.3", "color": "Green", "version": "AA"},
  {"id": "ST4-04", "name": "Palmon", "cardImage": "./assets/images/cards/ST4-04.png", "cardType": "Digimon", "dp": "2000", "playCost": "3", "digivolveCost1": "0 from Lv.2", "digivolveCost2": "-", "cardLv": "Lv.3", "form": "Rookie", "attribute": "Data", "type": "Vegetation", "rarity": "C", "cardNumber": "ST4-04", "effect": "-", "digivolveEffect": "[When Attacking] If you attack an opponent's Digimon, this Digimon gets +2000 DP for the turn.", "securityEffect": "-", "notes": "\u25b9Starter Deck, GIGA GREEN[ST-4]", "color": "Green", "version": "Normal"},
  {"id": "ST4-05", "name": "Kunemon", "cardImage": "./assets/images/cards/ST4-05.png", "cardType": "Digimon", "dp": "5000", "playCost": "4", "digivolveCost1": "0 from Lv.2", "digivolveCost2": "-", "cardLv": "Lv.3", "form": "Rookie", "attribute": "Virus", "type": "Larva", "rarity": "C", "cardNumber": "ST4-05", "effect": "-", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, GIGA GREEN[ST-4]", "color": "Green", "version": "Normal"},
  {"id": "ST4-06", "name": "Togemon", "cardImage": "./assets/images/cards/ST4-06.png", "cardType": "Digimon", "dp": "4000", "playCost": "4", "digivolveCost1": "2 from Lv.3", "digivolveCost2": "-", "cardLv": "Lv.4", "form": "Champion", "attribute": "Data", "type": "Vegetation", "rarity": "C", "cardNumber": "ST4-06", "effect": "-", "digivolveEffect": "[When Attacking] If you attack an opponent's Digimon, this Digimon gets +2000 DP for the turn.", "securityEffect": "-", "notes": "\u25b9Starter Deck, GIGA GREEN[ST-4]", "color": "Green", "version": "Normal"},
  {"id": "ST4-07", "name": "Kuwagamon", "cardImage": "./assets/images/cards/ST4-07.png", "cardType": "Digimon", "dp": "6000", "playCost": "5", "digivolveCost1": "2 from Lv.3", "digivolveCost2": "-", "cardLv": "Lv.4", "form": "Champion", "attribute": "Virus", "type": "Insectoid", "rarity": "C", "cardNumber": "ST4-07", "effect": "-", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, GIGA GREEN[ST-4]", "color": "Green", "version": "Normal"},
  {"id": "ST4-08", "name": "Kabuterimon", "cardImage": "./assets/images/cards/ST4-08.png", "cardType": "Digimon", "dp": "5000", "playCost": "6", "digivolveCost1": "1 from Lv.3", "digivolveCost2": "-", "cardLv": "Lv.4", "form": "Champion", "attribute": "Vaccine", "type": "Insectoid", "rarity": "U", "cardNumber": "ST4-08", "effect": "\uff1cBlocker\uff1e (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)[When Attacking] Lose 2 memory.", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, GIGA GREEN[ST-4]", "color": "Green", "version": "Normal"},
  {"id": "ST4-08_P1", "name": "Kabuterimon", "cardImage": "./assets/images/cards/ST4-08_P1.png", "cardType": "Digimon", "dp": "5000", "playCost": "6", "digivolveCost1": "1 from Lv.3", "digivolveCost2": "-", "cardLv": "Lv.4", "form": "Champion", "attribute": "Vaccine", "type": "Insectoid", "rarity": "U", "cardNumber": "ST4-08", "effect": "\uff1cBlocker\uff1e (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)[When Attacking] Lose 2 memory.", "digivolveEffect": "-", "securityEffect": "-", "notes": "2021 Online Regionals Participant Pack", "color": "Green", "version": "Stamp"},
  {"id": "ST4-08_P2", "name": "Kabuterimon", "cardImage": "./assets/images/cards/ST4-08_P2.png", "cardType": "Digimon", "dp": "5000", "playCost": "6", "digivolveCost1": "1 from Lv.3", "digivolveCost2": "-", "cardLv": "Lv.4", "form": "Champion", "attribute": "Vaccine", "type": "Insectoid", "rarity": "U", "cardNumber": "ST4-08", "effect": "\uff1cBlocker\uff1e (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)[When Attacking] Lose 2 memory.", "digivolveEffect": "-", "securityEffect": "-", "notes": "2021 Finalist Card Set", "color": "Green", "version": "Stamp"},
  {"id": "ST4-08_P3", "name": "Kabuterimon", "cardImage": "./assets/images/cards/ST4-08_P3.png", "cardType": "Digimon", "dp": "5000", "playCost": "6", "digivolveCost1": "1 from Lv.3", "digivolveCost2": "-", "cardLv": "Lv.4", "form": "Champion", "attribute": "Vaccine", "type": "Insectoid", "rarity": "U", "cardNumber": "ST4-08", "effect": "\uff1cBlocker\uff1e (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)[When Attacking] Lose 2 memory.", "digivolveEffect": "-", "securityEffect": "-", "notes": "2021 Champion Card Set", "color": "Green", "version": "Stamp"},
  {"id": "ST4-08_P4", "name": "Kabuterimon", "cardImage": "./assets/images/cards/ST4-08_P4.png", "cardType": "Digimon", "dp": "5000", "playCost": "6", "digivolveCost1": "1 from Lv.3", "digivolveCost2": "-", "cardLv": "Lv.4", "form": "Champion", "attribute": "Vaccine", "type": "Insectoid", "rarity": "U", "cardNumber": "ST4-08", "effect": "\uff1cBlocker\uff1e (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)[When Attacking] Lose 2 memory.", "digivolveEffect": "-", "securityEffect": "-", "notes": "Judge Pack", "color": "Green", "version": "Stamp"},
  {"id": "ST4-09", "name": "Okuwamon", "cardImage": "./assets/images/cards/ST4-09.png", "cardType": "Digimon", "dp": "7000", "playCost": "6", "digivolveCost1": "2 from Lv.4", "digivolveCost2": "-", "cardLv": "Lv.5", "form": "Ultimate", "attribute": "Virus", "type": "Insectoid", "rarity": "C", "cardNumber": "ST4-09", "effect": "-", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, GIGA GREEN[ST-4]", "color": "Green", "version": "Normal"},
  {"id": "ST4-10", "name": "Lillymon", "cardImage": "./assets/images/cards/ST4-10.png", "cardType": "Digimon", "dp": "7000", "playCost": "6", "digivolveCost1": "3 from Lv.4", "digivolveCost2": "-", "cardLv": "Lv.5", "form": "Ultimate", "attribute": "Data", "type": "Fairy", "rarity": "U", "cardNumber": "ST4-10", "effect": "[When Digivolving] Reveal the top 5 cards of your deck. Add 1 level 6 or higher Digimon card among them to your hand. Place the remaining cards at the bottom of your deck in any order.", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, GIGA GREEN[ST-4]", "color": "Green", "version": "Normal"},
  {"id": "ST4-10_P1", "name": "Lillymon", "cardImage": "./assets/images/cards/ST4-10_P1.png", "cardType": "Digimon", "dp": "7000", "playCost": "6", "digivolveCost1": "3 from Lv.4", "digivolveCost2": "-", "cardLv": "Lv.5", "form": "Ultimate", "attribute": "Data", "type": "Fairy", "rarity": "U", "cardNumber": "ST4-10", "effect": "[When Digivolving] Reveal the top 5 cards of your deck. Add 1 level 6 or higher Digimon card among them to your hand. Place the remaining cards at the bottom of your deck in any order.", "digivolveEffect": "-", "securityEffect": "-", "notes": "Official Tournament Pack Vol.3", "color": "Green", "version": "AA"},
  {"id": "ST4-11", "name": "MegaKabuterimon", "cardImage": "./assets/images/cards/ST4-11.png", "cardType": "Digimon", "dp": "7000", "playCost": "7", "digivolveCost1": "3 from Lv.4", "digivolveCost2": "-", "cardLv": "Lv.5", "form": "Ultimate", "attribute": "Vaccine", "type": "Insectoid", "rarity": "R", "cardNumber": "ST4-11", "effect": "-", "digivolveEffect": "[Your Turn][Once Per Turn] When this Digimon deletes an opponent's Digimon in battle and survives, trash the top card of your opponent's security stack.", "securityEffect": "-", "notes": "\u25b9Starter Deck, GIGA GREEN[ST-4]", "color": "Green", "version": "Normal"},
  {"id": "ST4-12", "name": "Rosemon", "cardImage": "./assets/images/cards/ST4-12.png", "cardType": "Digimon", "dp": "11000", "playCost": "10", "digivolveCost1": "3 from Lv.5", "digivolveCost2": "-", "cardLv": "Lv.6", "form": "Mega", "attribute": "Data", "type": "Fairy", "rarity": "R", "cardNumber": "ST4-12", "effect": "[When Digivolving] 1 of your opponent's Digimon can't attack or block until the end of their next turn.", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, GIGA GREEN[ST-4]", "color": "Green", "version": "Normal"},
  {"id": "ST4-13", "name": "HerculesKabuterimon", "cardImage": "./assets/images/cards/ST4-13.png", "cardType": "Digimon", "dp": "12000", "playCost": "12", "digivolveCost1": "4 from Lv.5", "digivolveCost2": "-", "cardLv": "Lv.6", "form": "Mega", "attribute": "Vaccine", "type": "Insectoid", "rarity": "SR", "cardNumber": "ST4-13", "effect": "\uff1cPiercing\uff1e (When this Digimon attacks and deletes an opponent's Digimon and survives the battle, it performs any security checks it normally would.)[Main] \uff1cDigi-Burst 2\uff1e (Trash 2 of this Digimon's Digivolution cards to activate the effect below.)\u30fbSuspend 1 of your opponent's Digimon.", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, GIGA GREEN[ST-4]", "color": "Green", "version": "Normal"},
  {"id": "ST4-13_P1", "name": "HerculesKabuterimon", "cardImage": "./assets/images/cards/ST4-13_P1.png", "cardType": "Digimon", "dp": "12000", "playCost": "12", "digivolveCost1": "4 from Lv.5", "digivolveCost2": "-", "cardLv": "Lv.6", "form": "Mega", "attribute": "Vaccine", "type": "Insectoid", "rarity": "SR", "cardNumber": "ST4-13", "effect": "\uff1cPiercing\uff1e (When this Digimon attacks and deletes an opponent's Digimon and survives the battle, it performs any security checks it normally would.)[Main] \uff1cDigi-Burst 2\uff1e (Trash 2 of this Digimon's Digivolution cards to activate the effect below.)\u30fbSuspend 1 of your opponent's Digimon.", "digivolveEffect": "-", "securityEffect": "-", "notes": "Event Pack 2", "color": "Green", "version": "AA"},
  {"id": "ST4-14", "name": "Izzy Izumi", "cardImage": "./assets/images/cards/ST4-14.png", "cardType": "Tamer", "dp": "-", "playCost": "2", "digivolveCost1": "-", "digivolveCost2": "-", "cardLv": "", "form": "-", "attribute": "-", "type": "-", "rarity": "R", "cardNumber": "ST4-14", "effect": "[Your Turn] When one of your opponent's Digimon becomes suspended, you may suspend this Tamer to gain 1 memory.", "digivolveEffect": "-", "securityEffect": "[Security] Play this card without paying its memory cost.", "notes": "\u25b9Starter Deck, GIGA GREEN[ST-4]", "color": "Green", "version": "Normal"},
  {"id": "ST4-15", "name": "Needle Spray", "cardImage": "./assets/images/cards/ST4-15.png", "cardType": "Option", "dp": "-", "playCost": "2", "digivolveCost1": "-", "digivolveCost2": "-", "cardLv": "", "form": "-", "attribute": "-", "type": "-", "rarity": "C", "cardNumber": "ST4-15", "effect": "[Main] Suspend 1 of your opponent's Digimon.", "digivolveEffect": "-", "securityEffect": "[Security] Activate this card's [Main] effect. Then, add this card to your hand.", "notes": "\u25b9Starter Deck, GIGA GREEN[ST-4]", "color": "Green", "version": "Normal"},
  {"id": "ST4-16", "name": "Electro Shocker", "cardImage": "./assets/images/cards/ST4-16.png", "cardType": "Option", "dp": "-", "playCost": "5", "digivolveCost1": "-", "digivolveCost2": "-", "cardLv": "", "form": "-", "attribute": "-", "type": "-", "rarity": "U", "cardNumber": "ST4-16", "effect": "[Main] Return 1 of your opponent's suspended Digimon to its owner's hand. Trash all of the digivolution cards of that Digimon.", "digivolveEffect": "-", "securityEffect": "[Security] Activate this card's [Main] effect.", "notes": "\u25b9Starter Deck, GIGA GREEN[ST-4]", "color": "Green", "version": "Normal"}
];
