import {ICard} from "../../app/models";

export const ST05CardList: ICard[] = [
  {"id": "ST5-01", "name": "Kapurimon", "cardImage": "assets/images/cards/ST5-01.png", "cardType": "Digi-Egg", "dp": "-", "playCost": "-", "digivolveCost1": "-", "digivolveCost2": "-", "cardLv": "Lv.2", "form": "In-Training", "attribute": "-", "type": "Lesser", "rarity": "U", "cardNumber": "ST5-01", "effect": "-", "digivolveEffect": "[Your Turn] While this Digimon has \uff1cBlocker\uff1e, it gets +1000 DP.", "securityEffect": "-", "notes": "\u25b9Starter Deck, MACHINE BLACK[ST-5]", "color": "Black", "version": "Normal"},
  {"id": "ST5-02", "name": "Jazamon", "cardImage": "assets/images/cards/ST5-02.png", "cardType": "Digimon", "dp": "4000", "playCost": "2", "digivolveCost1": "1 from Lv.2", "digivolveCost2": "-", "cardLv": "Lv.3", "form": "Rookie", "attribute": "Data", "type": "Bird Dragon", "rarity": "C", "cardNumber": "ST5-02", "effect": "-", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, MACHINE BLACK[ST-5]", "color": "Black", "version": "Normal"},
  {"id": "ST5-03", "name": "Agumon", "cardImage": "assets/images/cards/ST5-03.png", "cardType": "Digimon", "dp": "1000", "playCost": "3", "digivolveCost1": "0 from Lv.2", "digivolveCost2": "-", "cardLv": "Lv.3", "form": "Rookie", "attribute": "Vaccine", "type": "Reptile", "rarity": "U", "cardNumber": "ST5-03", "effect": "\uff1cBlocker\uff1e (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, MACHINE BLACK[ST-5]", "color": "Black", "version": "Normal"},
  {"id": "ST5-03_P1", "name": "Agumon", "cardImage": "assets/images/cards/ST5-03_P1.png", "cardType": "Digimon", "dp": "1000", "playCost": "3", "digivolveCost1": "0 from Lv.2", "digivolveCost2": "-", "cardLv": "Lv.3", "form": "Rookie", "attribute": "Vaccine", "type": "Reptile", "rarity": "U", "cardNumber": "ST5-03", "effect": "\uff1cBlocker\uff1e (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)", "digivolveEffect": "-", "securityEffect": "-", "notes": "Official Tournament Pack Vol.3", "color": "Black", "version": "AA"},
  {"id": "ST5-04", "name": "ToyAgumon", "cardImage": "assets/images/cards/ST5-04.png", "cardType": "Digimon", "dp": "2000", "playCost": "3", "digivolveCost1": "0 from Lv.2", "digivolveCost2": "-", "cardLv": "Lv.3", "form": "Rookie", "attribute": "Virus", "type": "Puppet", "rarity": "C", "cardNumber": "ST5-04", "effect": "-", "digivolveEffect": "[End of Opponent's Turn] If your opponent didn't attack with a Digimon this turn, trigger \uff1cDraw 1\uff1e. (Draw 1 card from your deck.)", "securityEffect": "-", "notes": "\u25b9Starter Deck, MACHINE BLACK[ST-5]", "color": "Black", "version": "Normal"},
  {"id": "ST5-05", "name": "Commandramon", "cardImage": "assets/images/cards/ST5-05.png", "cardType": "Digimon", "dp": "5000", "playCost": "4", "digivolveCost1": "0 from Lv.2", "digivolveCost2": "-", "cardLv": "Lv.3", "form": "Rookie", "attribute": "Virus", "type": "Cyborg/D-Brigade", "rarity": "C", "cardNumber": "ST5-05", "effect": "-", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, MACHINE BLACK[ST-5]", "color": "Black", "version": "Normal"},
  {"id": "ST5-06", "name": "Greymon", "cardImage": "assets/images/cards/ST5-06.png", "cardType": "Digimon", "dp": "4000", "playCost": "4", "digivolveCost1": "2 from Lv.3", "digivolveCost2": "-", "cardLv": "Lv.4", "form": "Champion", "attribute": "Virus", "type": "Dinosaur", "rarity": "C", "cardNumber": "ST5-06", "effect": "-", "digivolveEffect": "[End of Opponent's Turn] If your opponent didn't attack with a Digimon this turn, trigger \uff1cDraw 1\uff1e. (Draw 1 card from your deck.)", "securityEffect": "-", "notes": "\u25b9Starter Deck, MACHINE BLACK[ST-5]", "color": "Black", "version": "Normal"},
  {"id": "ST5-07", "name": "Jazardmon", "cardImage": "assets/images/cards/ST5-07.png", "cardType": "Digimon", "dp": "6000", "playCost": "5", "digivolveCost1": "2 from Lv.3", "digivolveCost2": "-", "cardLv": "Lv.4", "form": "Champion", "attribute": "Data", "type": "Machine Dragon", "rarity": "C", "cardNumber": "ST5-07", "effect": "-", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, MACHINE BLACK[ST-5]", "color": "Black", "version": "Normal"},
  {"id": "ST5-08", "name": "DarkTyrannomon", "cardImage": "assets/images/cards/ST5-08.png", "cardType": "Digimon", "dp": "5000", "playCost": "6", "digivolveCost1": "1 from Lv.3", "digivolveCost2": "-", "cardLv": "Lv.4", "form": "Champion", "attribute": "Virus", "type": "Dinosaur", "rarity": "U", "cardNumber": "ST5-08", "effect": "\uff1cBlocker\uff1e (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)[When Attacking] Lose 2 memory.", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, MACHINE BLACK[ST-5]", "color": "Black", "version": "Normal"},
  {"id": "ST5-08_P1", "name": "DarkTyrannomon", "cardImage": "assets/images/cards/ST5-08_P1.png", "cardType": "Digimon", "dp": "5000", "playCost": "6", "digivolveCost1": "1 from Lv.3", "digivolveCost2": "-", "cardLv": "Lv.4", "form": "Champion", "attribute": "Virus", "type": "Dinosaur", "rarity": "U", "cardNumber": "ST5-08", "effect": "\uff1cBlocker\uff1e (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)[When Attacking] Lose 2 memory.", "digivolveEffect": "-", "securityEffect": "-", "notes": "Judge Pack", "color": "Black", "version": "Stamp"},
  {"id": "ST5-09", "name": "MetalGreymon", "cardImage": "assets/images/cards/ST5-09.png", "cardType": "Digimon", "dp": "7000", "playCost": "6", "digivolveCost1": "3 from Lv.4", "digivolveCost2": "-", "cardLv": "Lv.5", "form": "Ultimate", "attribute": "Virus", "type": "Cyborg", "rarity": "U", "cardNumber": "ST5-09", "effect": "[When Digivolving] Until the end of your opponent's next turn, 1 of your Digimon gains \uff1cBlocker\uff1e. (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, MACHINE BLACK[ST-5]", "color": "Black", "version": "Normal"},
  {"id": "ST5-10", "name": "MetalTyrannomon", "cardImage": "assets/images/cards/ST5-10.png", "cardType": "Digimon", "dp": "9000", "playCost": "6", "digivolveCost1": "3 from Lv.4", "digivolveCost2": "-", "cardLv": "Lv.5", "form": "Ultimate", "attribute": "Virus", "type": "Cyborg", "rarity": "C", "cardNumber": "ST5-10", "effect": "-", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, MACHINE BLACK[ST-5]", "color": "Black", "version": "Normal"},
  {"id": "ST5-11", "name": "Megadramon", "cardImage": "assets/images/cards/ST5-11.png", "cardType": "Digimon", "dp": "7000", "playCost": "7", "digivolveCost1": "3 from Lv.4", "digivolveCost2": "-", "cardLv": "Lv.5", "form": "Ultimate", "attribute": "Virus", "type": "Cyborg", "rarity": "R", "cardNumber": "ST5-11", "effect": "-", "digivolveEffect": "\uff1cBlocker\uff1e (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead.)", "securityEffect": "-", "notes": "\u25b9Starter Deck, MACHINE BLACK[ST-5]", "color": "Black", "version": "Normal"},
  {"id": "ST5-12", "name": "Machinedramon", "cardImage": "assets/images/cards/ST5-12.png", "cardType": "Digimon", "dp": "11000", "playCost": "10", "digivolveCost1": "3 from Lv.5", "digivolveCost2": "-", "cardLv": "Lv.6", "form": "Mega", "attribute": "Virus", "type": "Machine", "rarity": "R", "cardNumber": "ST5-12", "effect": "[When Digivolving] Up to 2 of your Digimon gain \uff1cReboot\uff1e  (Unsuspend this Digimon during your opponent's unsuspend phase) until the end of your opponent's next turn.", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, MACHINE BLACK[ST-5]", "color": "Black", "version": "Normal"},
  {"id": "ST5-13", "name": "BlitzGreymon", "cardImage": "assets/images/cards/ST5-13.png", "cardType": "Digimon", "dp": "12000", "playCost": "12", "digivolveCost1": "4 from Lv.5", "digivolveCost2": "-", "cardLv": "Lv.6", "form": "Mega", "attribute": "Virus", "type": "Cyborg", "rarity": "SR", "cardNumber": "ST5-13", "effect": "\uff1cSecurity Attack +1\uff1e (This Digimon checks 1 additional security card.)[Main] \uff1cDigi-Burst 2\uff1e (Trash 2 of this Digimon's Digivolution cards to activate the effect below.)\u30fb1 of your Digimon gets +4000 DP until the end of your opponent's next turn.", "digivolveEffect": "-", "securityEffect": "-", "notes": "\u25b9Starter Deck, MACHINE BLACK[ST-5]", "color": "Black", "version": "Normal"},
  {"id": "ST5-14", "name": "Tai Kamiya", "cardImage": "assets/images/cards/ST5-14.png", "cardType": "Tamer", "dp": "-", "playCost": "2", "digivolveCost1": "-", "digivolveCost2": "-", "cardLv": "", "form": "-", "attribute": "-", "type": "-", "rarity": "R", "cardNumber": "ST5-14", "effect": "[Opponent's Turn] When you use \uff1cBlocker\uff1e to suspend one of your Digimon, you may suspend this Tamer to unsuspend 1 of your Digimon.", "digivolveEffect": "-", "securityEffect": "[Security] Play this card without paying its memory cost.", "notes": "\u25b9Starter Deck, MACHINE BLACK[ST-5]", "color": "Black", "version": "Normal"},
  {"id": "ST5-15", "name": "Laser Eye", "cardImage": "assets/images/cards/ST5-15.png", "cardType": "Option", "dp": "-", "playCost": "4", "digivolveCost1": "-", "digivolveCost2": "-", "cardLv": "", "form": "-", "attribute": "-", "type": "-", "rarity": "C", "cardNumber": "ST5-15", "effect": "[Main] Trigger \uff1cDe-Digivolve 1\uff1e on up to 2 of your opponent's Digimon. (Trash a card from the top of one of your opponent's Digimon. If it has no digivolution cards, or becomes a level 3 Digimon, you can't trash any more cards.)", "digivolveEffect": "-", "securityEffect": "[Security] Activate this card's [Main] effect.", "notes": "\u25b9Starter Deck, MACHINE BLACK[ST-5]", "color": "Black", "version": "Normal"},
  {"id": "ST5-16", "name": "Dark Side Attack", "cardImage": "assets/images/cards/ST5-16.png", "cardType": "Option", "dp": "-", "playCost": "5", "digivolveCost1": "-", "digivolveCost2": "-", "cardLv": "", "form": "-", "attribute": "-", "type": "-", "rarity": "U", "cardNumber": "ST5-16", "effect": "[Main] Delete 1 of your opponent's Digimon with a play cost of 7 or less.", "digivolveEffect": "-", "securityEffect": "[Security] Activate this card's [Main] effect.", "notes": "\u25b9Starter Deck, MACHINE BLACK[ST-5]", "color": "Black", "version": "Normal"}
];
